#pragma once
#include "types.h"
#include "memoryPool.h"

namespace Input
{
	enum MouseButton
	{
		MouseLeft = 0,
		MouseRight,
		MouseMiddle,
		MouseCount
	};

	enum Keys
	{
		KEY_BACKSPACE = 8,
		KEY_TAB = 9,
		KEY_DELETE = 127,
		KEY_SHIFT = 16,
		KEY_RETURN = 13,
		KEY_ESC = 27,
		KEY_CONTROL = 17,

		KEY_LEFT  = 37,
		KEY_UP    = 38,
		KEY_RIGHT = 39,
		KEY_DOWN  = 40,

		KEY_F1  = 112,
		KEY_F2  = 113,
		KEY_F3  = 114,
		KEY_F4  = 115,
		KEY_F5  = 116,
		KEY_F6  = 117,
		KEY_F7  = 118,
		KEY_F8  = 119,
		KEY_F9  = 120,
		KEY_F10 = 121,
		KEY_F11 = 122,
		KEY_F12 = 123,
	};

	void init(void* winData);
	//call at the end of the frame to clear out buffers [handled by the engine if using the default renderer]
	void finish();

	//OS interface (set from the windowing system).
	void setMouseButtonState(MouseButton button, bool buttonIsDown);
	void setKeyState(u32 key, bool keyIsDown);
	void addChar(char c);

	void incMouseWheel(s32 change);
	void setMousePos(s32 x, s32 y);
	void getMouseDelta(s32* dx, s32* dy);

	void setActive(bool active);
	bool isActive();

	////////////////////////////////////////////////
	//App interface.
	////////////////////////////////////////////////
	//is the key down
	bool keyDown(u32 key);
	//has the key been 'pressed' (i.e. just pressed down)
	//'WithRepeat' will trigger a key pressed on every key down event
	//generated by the OS.
	bool keyPressedWithRepeat(u32 key);
	bool keyPressed(u32 key);
	//get the characters input since last frame.
	char* getCharInput();
	//mouse
	bool getMouseButtonState(MouseButton button);
	void getMousePos(s32& x, s32& y);
	s32  getMouseWheelDelta();

	int mapVirtualKey(int keyCode);
};